version: '3.8'

services:
  discord-bot:
    build: .
    container_name: discord-summary-bot
    restart: unless-stopped
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./logs:/app/logs  # ログファイル用（オプション）
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
